In [ ]:
import os
import pickle

path = "/media/NLP/simple_manipulation"
train_path = os.path.join(path, "train")
val_path = os.path.join(path, "val")
test_path = os.path.join(path, "test")

train = os.listdir(train_path)
train = train[0:100]
print(train)

In [ ]:
!ls $element_path

In [ ]:
element_path = os.path.join(train_path, train[1])
action_path = os.path.join(element_path, "action.pkl")
assert os.path.exists(action_path)

with open(action_path, "rb") as f:
    action = pickle.load(f)

action

In [ ]:
from pose_quantizer import PoseQuantizer

pq = PoseQuantizer(-0.5, 0.75, 100)
print("Original: " + str(action['pose0_position'][0]))
enc = pq.encode_array(action['pose0_position'][0])
print("Encoded: " + str(enc))
dec = pq.decode_array(enc)
print("Decoded: " + str(dec))

In [ ]:
element_path = os.path.join(train_path, train[1])
trajectory_path = os.path.join(element_path, "trajectory.pkl")
assert os.path.exists(trajectory_path)

with open(trajectory_path, "rb") as f:
    trajectory = pickle.load(f)


trajectory

In [ ]:
for data in train:
    element_path = os.path.join(train_path, data)
    trajectory_path = os.path.join(element_path, "trajectory.pkl")
    assert os.path.exists(trajectory_path)

    with open(trajectory_path, "rb") as f:
        trajectory = pickle.load(f)
    print(trajectory['action_bounds'])

#trajectory

In [11]:
from transformers import T5Tokenizer
import numpy as np
import sys

tokenizer = T5Tokenizer.from_pretrained(
        "t5-base", model_max_length=256, extra_ids=1200) 

res = tokenizer("action pose <extra_id_1177><extra_id_1171><extra_id_1143> rotation <extra_id_1140><extra_id_1140><extra_id_1140><extra_id_1199> action pose <extra_id_1177><extra_id_1150><extra_id_1142> rotation <extra_id_1140><extra_id_1140><extra_id_1199><extra_id_1114>", max_length=64, truncation=True, padding='max_length')['input_ids']

#tokenizer.decode(res)
res = np.array(res)
print(res)
masks = np.ones((res.shape[-1], res.shape[-1]))
masks = np.triu(masks, 1)
masks


ValueError: too many values to unpack (expected 2)

In [2]:
import process_data

path = "/media/NLP/simple_manipulation/train/"
element_path = os.path.join(path, '000000')
process_data.processDataPoint(element_path)

IMAGE SHAPE: (128, 256, 3)
IMAGE TENSOR SHAPE: (384, 384, 3)
[[[ 1.9577874  2.1309524  2.3437037]
  [ 1.9663497  2.1397057  2.3524182]
  [ 2.0091617  2.1834733  2.3959913]
  ...
  [ 2.040557   2.2155695  2.4279447]
  [ 1.9834745  2.1572127  2.3698473]
  [ 1.9064132  2.0784314  2.2914162]]

 [[ 1.9663497  2.1397057  2.3524182]
  [ 1.9535064  2.1265757  2.3393464]
  [ 1.923538   2.0959384  2.3088453]
  ...
  [ 1.5838969  1.7487161  1.9631662]
  [ 1.9363816  2.1090686  2.3219173]
  [ 2.0690982  2.2447479  2.4569933]]

 [[ 2.0063074  2.1805553  2.3930862]
  [ 1.9849015  2.1586719  2.3712997]
  [ 1.903559   2.0755134  2.288511 ]
  ...
  [ 1.1767083  1.3324386  1.5487388]
  [ 1.9135486  2.085726   2.2986784]
  [ 2.2060962  2.384804   2.5964267]]

 ...

 [[-2.117904  -2.0357144 -1.8044444]
  [-2.117904  -2.0357144 -1.8044444]
  [-2.117904  -2.0357144 -1.8044444]
  ...
  [-2.117904  -2.0357144 -1.8044444]
  [-2.117904  -2.0357144 -1.8044444]
  [-2.117904  -2.0357144 -1.8044444]]

 [[-2.117904 

pybullet build time: May 20 2022 19:45:31


[INFO] 17 tasks loaded
